# Fluentd Image with Custom Plugin Installation
image:
  repository: fluent/fluentd
  tag: v1.15.3-debian-1
  pullPolicy: IfNotPresent

# Extra init container to install the missing plugin
extraInitContainers:
  - name: install-plugins
    image: fluent/fluentd:v1.15.3-debian-1
    command: ["/bin/sh", "-c"]
    args:
      - "fluent-gem install fluent-plugin-remote_syslog"
    volumeMounts:
      - name: plugins
        mountPath: /fluentd/plugins

# Mount the installed plugins into Fluentd container
extraVolumeMounts:
  - name: plugins
    mountPath: /fluentd/plugins

extraVolumes:
  - name: plugins
    emptyDir: {}

# Fluentd Configuration for Collecting Kong Logs
fluentd:
  configMaps:
    fluentd-conf: |
      <source>
        @type tail
        path /var/log/containers/*kong*.log
        pos_file /var/log/fluentd-kong.pos
        tag kong
        format json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
        read_from_head true
      </source>

      <match kong>
        @type remote_syslog
        host YOUR_SIM_SERVER_IP  # Change to your SIM server IP or hostname
        port 514
        protocol udp
        tag kong
        facility user
        severity info
      </match>

# Enable Debugging for Fluentd (Optional)
env:
  FLUENTD_ARGS: "-vv"
